// o.js : v0.0.8 : http://o-js.com : MIT License
(function(){function q(a){return a.charAt(0).toUpperCase()+a.slice(1)}var m=this,r=m.o,a={};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=a),exports.o=a,exports.oJS=a):(m.o=a,m.oJS=a);a.noConflict=function(){m.o=r;return a};a.local=function(d,c,b){var e=a.has(d,c),g=d[c],f;try{f=b()}finally{e?d[c]=g:delete d[c]}return f};a.reader=function(d,c){c=c||{};c.writer=c.writer||a.writer(d,c);c.predicate=c.predicate||a.predicate(d);return function(){if(!c.predicate.call(this)){if(c.required)throw Error("...");
if(c.devoid){var a=c.devoid;a instanceof Function&&(a=a.call(this));c.writer.call(this,a)}else c.builder&&c.writer.call(this,this[c.builder].call(this))}return this[d]}};a.writer=function(d,c){c=c||{};c.augments&&(c.type=c.type||"object");return function(b){c.filter&&(b=c.filter.call(this,b));if(c.type)if("string"===typeof c.type||c.type instanceof String){if(typeof b!==c.type)throw Error("...");}else if(c.type instanceof Function){if(!c.type(b))throw Error("...");}else if(c.type instanceof a.Type)c.coerce?
b=c.type.coerce(b):c.type.validate(b);else throw Error("...");if(c.augments&&!(b instanceof c.augments))throw Error("...");var e=this[d];this[d]=b;return c.chain?this:e}};a.accessor=function(d,c){c=c||{};c.writer=c.writer||a.writer(d,c);c.reader=c.reader||a.reader(d,c);return function(a){return void 0!==a?c.writer.call(this,a):c.reader.call(this)}};a.predicate=function(d){return function(){return a.has(this,d)&&void 0!==this[d]}};a.clearer=function(a){return function(){delete this[a]}};a.proxy=function(a,
c){return function(){return this[a][c].apply(this[a],arguments)}};a.before=function(a,c){return function(){c.call(this);return a.apply(this,arguments)}};a.after=function(a,c){return function(){var b=a.apply(this,arguments);c.call(this);return b}};a.around=function(a,c){return function(){var b=this,e=Array.prototype.slice.call(arguments);e.unshift(function(){return a.apply(b,arguments)});return c.apply(b,e)}};a.construct=function(d,c){a.merge(d.prototype,c);return d};a.augment=function(d,c,b){var e=
a.around(d,c);b=b?a.merge({},c.prototype,b):a.clone(c.prototype);b.__proto__=d.prototype;e.prototype=b;return e};a.merge=function(){for(var d=Array.prototype.slice.call(arguments),c=d.shift();d.length;){var b=d.shift(),e;for(e in b)a.has(b,e)&&(c[e]=b[e])}return c};a.clone=function(d){var c=a.merge({},d);c.__proto__=d.__proto__;c.constructor=d.constructor;return c};a.has=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};a.Type=a.construct(function(a){"function"===typeof a&&(a={validate:a});
if(a.validate)this._validateMethod=a.validate;else throw Error("...");a.message&&(this._messageMethod=a.message);a.coerce&&(this._coerceMethod=a.coerce);a.parent&&(this._parent=a.parent)},{check:function(a){return this._parent&&!this._parent.check(a)||!this._validateMethod(a)?!1:!0},validate:function(a){this._parent&&this._parent.validate(a);if(!this._validateMethod(a))throw Error("...");return!0},coerce:function(a){a=this.coerceOnly(a);if(!this._validateMethod(a))throw Error("...");return a},coerceOnly:function(a){this._parent&&
(a=this._parent.coerceOnly(a));this._coerceMethod&&(a=this._coerceMethod(a));return a},error:function(a){if(this._messageMethod)throw Error(this._messageMethod(a));throw Error('Validation failed for value "'+a+'"');},subtype:function(d){"function"===typeof d&&(d={validate:d});void 0===d.validate&&(d.validate=function(){return!0});return new a.Type(a.merge({parent:this},d))}});a.EqualType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){return a===c?!0:!1};a(b)});a.AnyType=a.augment(a.Type,
function(a,c,b){b=b||{};b.validate=function(a){for(var d=0,b=c.length;d<b;d++)if(c[d].check(a))return!0;return!1};a(b)});a.AllType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){for(var d=0,b=c.length;d<b;d++)if(!c[d].check(a))return!1;return!0};a(b)});a.NoneType=a.augment(a.Type,function(d,c,b){b=b||{};var e=new a.AnyType(c);b.validate=function(a){return e.check(a)?!1:!0};d(b)});a.NotType=a.augment(a.NoneType,function(a,c,b){a([c],b)});a.EnumType=a.augment(a.Type,function(a,c,b){b=
b||{};b.validate=function(a){for(var d=0,b=c.length;d<b;d++)if(a===c[d])return!0;return!1};a(b)});a.TypeOfType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){return typeof a===c?!0:!1};a(b)});a.InstanceOfType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){return a instanceof c?!0:!1};a(b)});a.undefinedType=new a.EqualType(void 0);a.definedType=new a.NotType(a.undefinedType);a.nullType=new a.EqualType(null);a.booleanPrimitiveType=new a.TypeOfType("boolean");a.booleanObjectType=
new a.InstanceOfType(Boolean);a.booleanType=new a.AnyType([a.booleanPrimitiveType,a.booleanObjectType]);a.stringPrimitiveType=new a.TypeOfType("string");a.stringObjectType=new a.InstanceOfType(String);a.stringType=new a.AnyType([a.stringPrimitiveType,a.stringObjectType]);a.nonEmptyStringType=a.stringType.subtype(function(a){return 0<a.length?!0:!1});a.numberPrimitiveType=new a.TypeOfType("number");a.numberObjectType=new a.InstanceOfType(Number);a.numberType=new a.AnyType([a.numberPrimitiveType,a.numberObjectType]);
a.integerType=a.numberType.subtype(function(a){return Math.floor(a)===a+0?!0:!1});a.positiveType=a.numberType.subtype(function(a){return 0<a?!0:!1});a.negativeType=a.numberType.subtype(function(a){return 0>a?!0:!1});a.nonZeroType=a.numberType.subtype(function(a){return 0!==a?!0:!1});a.objectType=new a.InstanceOfType(Object);a.functionType=new a.InstanceOfType(Function);a.arrayType=new a.InstanceOfType(Array);a.regExpType=new a.InstanceOfType(RegExp);a.dateType=new a.InstanceOfType(Date);a.DuckType=
a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(d){if(!a.objectType.check(d))return!1;if(a.arrayType.check(c)){for(var b=0,f=c.length;b<f;b++)if(void 0===d[c[b]])return!1;return!0}if(a.objectType.check(c)){for(b in c)if(void 0===d[b]||!c[b].check(d[b]))return!1;return!0}return!1};d(b)});a.ArrayOfType=a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(b){if(!a.arrayType.check(b))return!1;for(var d=0,f=b.length;d<f;d++)if(!c.check(b[d]))return!1;return!0};d(b)});a.ObjectOfType=
a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(b){if(!a.objectType.check(b))return!1;for(var d in b)if(!c.check(b[d]))return!1;return!0};d(b)});a.PatternType=a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(b){return a.stringType.check(b)?c.test(b):!1};d(b)});var h=new a.AnyType([a.booleanType,a.nonEmptyStringType]),h={key:{type:a.nonEmptyStringType,required:!0},argKey:{type:new a.AnyType([a.nonEmptyStringType,a.nullType]),devoid:function(){return this.key()}},valueKey:{type:a.nonEmptyStringType,
devoid:function(){return"_"+this.key()}},devoid:{type:a.definedType},builder:{type:h,devoid:!1,filter:function(a){!0===a&&(a="build"+q(this.key()));return a}},required:{type:a.booleanType,devoid:!1},type:{type:new a.AnyType([new a.EnumType("undefined object boolean number string function".split(" ")),new a.InstanceOfType(a.Type),a.functionType])},coerce:{type:a.booleanType,devoid:!1},filter:{type:a.functionType},augments:{type:a.functionType},chain:{type:a.booleanType,devoid:!1},reader:{type:h,devoid:!0,
filter:function(a){!0===a&&(a=this.key());return a}},writer:{type:h,devoid:!1,filter:function(a){!0===a&&(a=this.key());return a}},predicate:{type:h,devoid:!1,filter:function(a){!0===a&&(a="has"+q(this.key()));return a}},clearer:{type:h,devoid:!1,filter:function(a){!0===a&&(a="clear"+q(this.key()));return a}},proxies:{type:new a.ObjectOfType(a.nonEmptyStringType)}},n={},p={},k;for(k in h)n[k]=a.writer("_"+k,h[k]),p[k]=a.reader("_"+k,a.merge({writer:n[k]},h[k]));a.Attribute=a.construct(function(d){this._originalArgs=
a.clone(d);n.key.call(this,d.key);for(var c in d)n[c].call(this,d[c])},a.merge({readerMethod:a.reader("_readerMethod",{type:a.functionType,devoid:function(){return a.reader(this.valueKey(),{devoid:this.devoid(),builder:this.builder(),required:this.required(),writer:this.writerMethod(),predicate:this.predicateMethod()})}}),writerMethod:a.reader("_writerMethod",{type:a.functionType,devoid:function(){return a.writer(this.valueKey(),{type:this.type(),coerce:this.coerce(),filter:this.filter(),augments:this.augments(),
chain:this.chain()})}}),accessorMethod:a.reader("_accessorMethod",{type:a.functionType,devoid:function(){return a.accessor(this.valueKey(),{writer:this.writerMethod(),reader:this.readerMethod()})}}),predicateMethod:a.reader("_predicateMethod",{type:a.functionType,devoid:function(){return a.predicate(this.valueKey())}}),clearerMethod:a.reader("_clearerMethod",{type:a.functionType,devoid:function(){return a.clearer(this.valueKey())}}),proxyMethods:a.reader("_proxyMethods",{type:new a.ObjectOfType(a.functionType),
devoid:function(){var a={},c=this.proxies();if(void 0===c)return a;var b=this,e;for(e in c)a[e]=function(a){return function(){var c=b.getValue(this);return c[a].apply(c,arguments)}}(c[e]);return a}}),getValue:function(a){return this.readerMethod().call(a)},setValue:function(a,c){return this.writerMethod().call(a,c)},hasValue:function(a){return this.predicateMethod().call(a)},clearValue:function(a){return this.clearerMethod().call(a)},setValueFromArgs:function(a,c){if(null!==this.argKey()&&void 0!==
c[this.argKey()])return this.setValue(a,c[this.argKey()])},install:function(a,c){null!==this.writer()&&this.writer()===this.reader()?a[this.writer()]=this.accessorMethod():(null!==this.writer()&&(a[this.writer()]=this.writerMethod()),null!==this.reader()&&(a[this.reader()]=this.readerMethod()));null!==this.predicate()&&(a[this.predicate()]=this.predicateMethod());null!==this.clearer()&&(a[this.clearer()]=this.clearerMethod());var b=this.proxyMethods(),e;for(e in b)a[e]=b[e];c&&this.setValue(a,c)},
rebuild:function(d){return new this.constructor(a.merge({},this._originalArgs,d))}},p));var l=[];a.Trait=a.construct(function(a){for(var c=0,b=l.length;c<b;c++)l[c].setValueFromArgs(this,a)},{install:function(d,c){for(var b=this.traits(),e=0,g=b.length;e<g;e++)b[e].install(d);var b=this.attributes(),f;for(f in b)b[f].install(d);b=this.methods();for(f in b)d[f]=b[f];b=this.around();for(f in b)d[f]=a.around(d[f],b[f]);b=this.before();for(f in b)d[f]=a.before(d[f],b[f]);b=this.after();for(f in b)d[f]=
a.after(d[f],b[f]);c&&this.setFromArgs(d,c)},setFromArgs:function(a,c){var b=this.attributes(),e;for(e in b)b[e].filter()||b[e].setValueFromArgs(a,c);for(e in b)b[e].filter()&&b[e].setValueFromArgs(a,c)},buildType:function(){var d={},c=this.attributes(),b;for(b in c){var e=c[b],g=e.type(),f=e.augments();if(g||f){var h=e.valueKey(),e=e.required(),f=f?new a.InstanceOfType(f):null,g=g instanceof a.Type?g:g instanceof Function?new a.Type({validate:g}):g?new a.TypeOfType(g):null,g=f&&g?new a.AllType([f,
g]):f?f:g;e||(g=new a.AnyType([a.undefinedType,g]));d[h]=g}}for(b in this.methods())d[b]=a.functionType;for(b in this.around())d[b]=a.functionType;for(b in this.before())d[b]=a.functionType;for(b in this.after())d[b]=a.functionType;d=new a.DuckType(d);c=this.traits();if(!c.length)return d;d=[d];b=0;for(h=c.length;b<h;b++)d.push(c[b].type());return new a.AllType(d)}});l=[{key:"traits",type:new a.ArrayOfType(new a.InstanceOfType(a.Trait)),devoid:function(){return[]}},{key:"attributes",type:new a.ObjectOfType(new a.InstanceOfType(a.Attribute)),
devoid:function(){return{}},filter:function(d){var c={},b;for(b in d){var e=d[b];e instanceof a.Attribute?e.key()!==b&&(e=e.rebuild({key:b})):e=new a.Attribute(a.merge({},e,{key:b}));c[b]=e}return c}},{key:"methods",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}}},{key:"around",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}}},{key:"before",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}}},{key:"after",type:new a.ObjectOfType(a.functionType),
devoid:function(){return{}}},{key:"type",type:new a.InstanceOfType(a.Type),builder:!0,argKey:null}];k=a.Trait.prototype;h=0;for(p=l.length;h<p;h++)l[h]=new a.Attribute(l[h]),l[h].install(k);var s=new a.Trait({attributes:{type:{type:new a.InstanceOfType(a.Type),builder:!0,argKey:null},trait:{type:new a.InstanceOfType(a.Trait),required:!0}},methods:{buildType:function(){return new a.InstanceOfType(this)}}});a.Constructor=a.construct(function(d){var c=new a.Trait(d);d=function(a){c.setFromArgs(this,
a)};c.install(d.prototype);s.install(d,{trait:c});return d})}).call(this);
