(function(){function n(a){return a.charAt(0).toUpperCase()+a.slice(1)}var k=this,p=k.o,a={};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=a),exports.o=a,exports.oJS=a):(k.o=a,k.oJS=a);a.noConflict=function(){k.o=p;return a};a.reader=function(b,d){d=d||{};d.writer=d.writer||a.writer(b,d);d.predicate=d.predicate||a.predicate(b);return function(){if(!d.predicate.call(this)){if(d.required)throw Error("...");if(void 0!==d.devoid){var a=d.devoid;a instanceof
Function&&(a=a.call(this));d.writer.call(this,a)}}return this[b]}};a.writer=function(b,d){d=d||{};d.augments&&(d.type=d.type||"object");return function(c){d.filter&&(c=d.filter.call(this,c));if(d.type)if("string"===typeof d.type||d.type instanceof String){if(typeof c!==d.type)throw Error("...");}else if(d.type instanceof Function){if(!d.type(c))throw Error("...");}else if(d.type instanceof a.Type)d.coerce?c=d.type.coerce(c):d.type.validate(c);else throw Error("...");if(d.augments&&!(c instanceof d.augments))throw Error("...");
var e=this[b];this[b]=c;return d.chain?this:e}};a.accessor=function(b,d){d=d||{};d.writer=d.writer||a.writer(b,d);d.reader=d.reader||a.reader(b,d);return function(a){return void 0!==a?d.writer.call(this,a):d.reader.call(this)}};a.predicate=function(b){return function(){return a.has(this,b)&&void 0!==this[b]}};a.clearer=function(a){return function(){delete this[a]}};a.proxy=function(a,d){return function(){return this[a][d].apply(this[a],arguments)}};a.before=function(a,d){return function(){d.call(this);
return a.apply(this,arguments)}};a.after=function(a,d){return function(){var c=a.apply(this,arguments);d.call(this);return c}};a.around=function(a,d){return function(){var c=this,e=Array.prototype.slice.call(arguments);e.unshift(function(){return a.apply(c,arguments)});return d.apply(c,e)}};a.construct=function(b,d){a.merge(b.prototype,d);return b};a.augment=function(b,d,c){var e=a.around(b,d);c=c?a.merge({},d.prototype,c):a.clone(d.prototype);c.__proto__=b.prototype;e.prototype=c;return e};a.merge=
function(){for(var b=Array.prototype.slice.call(arguments),d=b.shift();b.length;){var c=b.shift(),e;for(e in c)a.has(c,e)&&(d[e]=c[e])}return d};a.clone=function(b){var d=a.merge({},b);d.__proto__=b.__proto__;d.constructor=b.constructor;return d};a.has=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)};a.Type=a.construct(function(a){"function"===typeof a&&(a={validate:a});if(a.validate)this.validateMethod=a.validate;else throw Error("...");a.message&&(this.messageMethod=a.message);a.coerce&&
(this.coerceMethod=a.coerce);a.parent&&(this.parent=a.parent)},{check:function(a){return this.parent&&!this.parent.check(a)||!this.validateMethod(a)?!1:!0},validate:function(a){this.parent&&this.parent.validate(a);if(!this.validateMethod(a))throw Error("...");return!0},coerceOnly:function(a){this.parent&&(a=this.parent.coerceOnly(a));this.coerceMethod&&(a=this.coerceMethod(a));return a},coerce:function(a){a=this.coerceOnly(a);if(!this.validateMethod(a))throw Error("...");return a},error:function(a){if(this.messageMethod)throw Error(this.messageMethod(a));
throw Error('Validation failed for value "'+a+'"');},subtype:function(b){"function"===typeof b&&(b={validate:b});void 0===b.validate&&(b.validate=function(){return!0});return new a.Type(a.merge({parent:this},b))}});a.EqualType=a.augment(a.Type,function(a,d,c){c=c||{};c.validate=function(a){return a===d?!0:!1};a(c)});a.AnyType=a.augment(a.Type,function(a,d,c){c=c||{};c.validate=function(a){for(var b=0,c=d.length;b<c;b++)if(d[b].check(a))return!0;return!1};a(c)});a.AllType=a.augment(a.Type,function(a,
d,c){c=c||{};c.validate=function(a){for(var b=0,c=d.length;b<c;b++)if(!d[b].check(a))return!1;return!0};a(c)});a.NoneType=a.augment(a.Type,function(b,d,c){c=c||{};var e=new a.AnyType(d);c.validate=function(a){return e.check(a)?!1:!0};b(c)});a.NotType=a.augment(a.NoneType,function(a,d,c){a([d],c)});a.EnumType=a.augment(a.Type,function(a,d,c){c=c||{};c.validate=function(a){for(var b=0,c=d.length;b<c;b++)if(a===d[b])return!0;return!1};a(c)});a.TypeOfType=a.augment(a.Type,function(a,d,c){c=c||{};c.validate=
function(a){return typeof a===d?!0:!1};a(c)});a.InstanceOfType=a.augment(a.Type,function(a,d,c){c=c||{};c.validate=function(a){return a instanceof d?!0:!1};a(c)});a.undefinedType=new a.EqualType(void 0);a.definedType=new a.NotType(a.undefinedType);a.nullType=new a.EqualType(null);a.isUndefined=function(b){return a.undefinedType.check(b)};a.isDefined=function(b){return a.definedType.check(b)};a.isNull=function(b){return a.nullType.check(b)};a.booleanPrimitiveType=new a.TypeOfType("boolean");a.booleanObjectType=
new a.InstanceOfType(Boolean);a.booleanType=new a.AnyType([a.booleanPrimitiveType,a.booleanObjectType]);a.isBooleanPrimitive=function(b){return a.booleanPrimitiveType.check(b)};a.isBooleanObject=function(b){return a.booleanObjectType.check(b)};a.isBoolean=function(b){return a.booleanType.check(b)};a.stringPrimitiveType=new a.TypeOfType("string");a.stringObjectType=new a.InstanceOfType(String);a.stringType=new a.AnyType([a.stringPrimitiveType,a.stringObjectType]);a.isStringPrimitive=function(b){return a.stringPrimitiveType.check(b)};
a.isStringObject=function(b){return a.stringObjectType.check(b)};a.isString=function(b){return a.stringType.check(b)};a.nonEmptyStringType=a.stringType.subtype(function(a){return 0<a.length?!0:!1});a.isNonEmptyString=function(b){return a.nonEmptyStringType.check(b)};a.numberPrimitiveType=new a.TypeOfType("number");a.numberObjectType=new a.InstanceOfType(Number);a.numberType=new a.AnyType([a.numberPrimitiveType,a.numberObjectType]);a.isNumberPrimitive=function(b){return a.numberPrimitiveType.check(b)};
a.isNumberObject=function(b){return a.numberObjectType.check(b)};a.isNumber=function(b){return a.numberType.check(b)};a.integerType=a.numberType.subtype(function(a){return Math.floor(a)===a+0?!0:!1});a.isInteger=function(b){return a.integerType.check(b)};a.positiveType=a.numberType.subtype(function(a){return 0<a?!0:!1});a.isPositive=function(b){return a.positiveType.check(b)};a.negativeType=a.numberType.subtype(function(a){return 0>a?!0:!1});a.isNegative=function(b){return a.negativeType.check(b)};
a.nonZeroType=a.numberType.subtype(function(a){return 0!==a?!0:!1});a.isNonZero=function(b){return a.nonZeroType.check(b)};a.objectType=new a.InstanceOfType(Object);a.functionType=new a.InstanceOfType(Function);a.arrayType=new a.InstanceOfType(Array);a.regExpType=new a.InstanceOfType(RegExp);a.dateType=new a.InstanceOfType(Date);a.isObject=function(b){return a.objectType.check(b)};a.isFunction=function(b){return a.functionType.check(b)};a.isArray=function(b){return a.arrayType.check(b)};a.isRegExp=
function(b){return a.regExpType.check(b)};a.isDate=function(b){return a.dateType.check(b)};a.DuckType=a.augment(a.Type,function(b,d,c){c=c||{};c.validate=function(b){if(!a.objectType.check(b))return!1;for(var c=0,g=d.length;c<g;c++)if(void 0===b[d[c]])return!1;return!0};b(c)});a.ArrayOfType=a.augment(a.Type,function(b,d,c){c=c||{};c.validate=function(b){if(!a.arrayType.check(b))return!1;for(var c=0,g=b.length;c<g;c++)if(!d.check(b[c]))return!1;return!0};b(c)});a.ObjectOfType=a.augment(a.Type,function(b,
d,c){c=c||{};c.validate=function(b){if(!a.objectType.check(b))return!1;for(var c in b)if(!d.check(b[c]))return!1;return!0};b(c)});var g=new a.AnyType([a.nullType,a.nonEmptyStringType]),g={key:{type:a.nonEmptyStringType,required:!0},argKey:{type:new a.AnyType([a.nonEmptyStringType,a.nullType]),devoid:function(){return this.key()}},valueKey:{type:a.nonEmptyStringType,devoid:function(){return"_"+this.key()}},devoid:{type:a.definedType},required:{type:a.booleanType,devoid:!1},type:{type:new a.AnyType([new a.EnumType("undefined object boolean number string function".split(" ")),
new a.InstanceOfType(a.Type),a.functionType])},coerce:{type:a.booleanType,devoid:!1},filter:{type:a.functionType},augments:{type:a.functionType},chain:{type:a.booleanType,devoid:!1},reader:{type:g,devoid:function(){return this.key()}},writer:{type:g,devoid:function(){return this.key()}},predicate:{type:g,filter:function(a){!0===a&&(a="has"+n(this.key()));return a},devoid:function(){return null}},clearer:{type:g,filter:function(a){!0===a&&(a="clear"+n(this.key()));return a},devoid:function(){return null}},
proxies:{type:new a.ObjectOfType(a.nonEmptyStringType)}},m={},l={},h;for(h in g)m[h]=a.writer("_"+h,g[h]),l[h]=a.reader("_"+h,a.merge({writer:m[h]},g[h]));a.Attribute=a.construct(function(a){for(var d in a)m[d].call(this,a[d])},a.merge({readerMethod:a.reader("_readerMethod",{type:a.functionType,devoid:function(){return a.reader(this.valueKey(),{devoid:this.devoid(),required:this.required(),writer:this.writerMethod(),predicate:this.predicateMethod()})}}),writerMethod:a.reader("_writerMethod",{type:a.functionType,
devoid:function(){return a.writer(this.valueKey(),{type:this.type(),coerce:this.coerce(),filter:this.filter(),augments:this.augments(),chain:this.chain()})}}),accessorMethod:a.reader("_accessorMethod",{type:a.functionType,devoid:function(){return a.accessor(this.valueKey(),{writer:this.writerMethod(),reader:this.readerMethod()})}}),predicateMethod:a.reader("_predicateMethod",{type:a.functionType,devoid:function(){return a.predicate(this.valueKey())}}),clearerMethod:a.reader("_clearerMethod",{type:a.functionType,
devoid:function(){return a.clearer(this.valueKey())}}),proxyMethods:a.reader("_proxyMethods",{type:new a.ObjectOfType(a.functionType),devoid:function(){var a={},d=this.proxies();if(void 0===d)return a;var c=this,e;for(e in d)a[e]=function(a){return function(){var b=c.getValue(this);return b[a].apply(b,arguments)}}(d[e]);return a}}),getValue:function(a){return this.readerMethod().call(a)},setValue:function(a,d){return this.writerMethod().call(a,d)},hasValue:function(a){return this.predicateMethod().call(a)},
clearValue:function(a){return this.clearerMethod().call(a)},setValueFromArgs:function(a,d){if(null!==this.argKey()&&void 0!==d[this.argKey()])return this.setValue(a,d[this.argKey()])},install:function(a){null!==this.writer()&&this.writer()===this.reader()?a[this.writer()]=this.accessorMethod():(null!==this.writer()&&(a[this.writer()]=this.writerMethod()),null!==this.reader()&&(a[this.reader()]=this.readerMethod()));null!==this.predicate()&&(a[this.predicate()]=this.predicateMethod());null!==this.clearer()&&
(a[this.clearer()]=this.clearerMethod());var d=this.proxyMethods(),c;for(c in d)a[c]=d[c]}},l));var j=[];a.Trait=a.construct(function(a){for(var d=0,c=j.length;d<c;d++)j[d].setValueFromArgs(this,a)},{install:function(b){for(var d=this.traits(),c=0,e=d.length;c<e;c++)d[c].install(b);d=this.attributes();c=0;for(e=d.length;c<e;c++)d[c].install(b);var c=this.methods(),f;for(f in c)b[f]=c[f];c=this.around();for(f in c)b[f]=a.around(b[f],c[f]);c=this.before();for(f in c)b[f]=a.before(b[f],c[f]);c=this.after();
for(f in c)b[f]=a.after(b[f],c[f])},setFromArgs:function(a,d){for(var c=this.attributes(),e=0,f=c.length;e<f;e++)c[e].setValueFromArgs(a,d)}});j.push(new a.Attribute({key:"traits",argKey:"with",type:new a.ArrayOfType(new a.InstanceOfType(a.Trait)),devoid:function(){return[]},writer:null}));j.push(new a.Attribute({key:"attributes",argKey:"has",type:new a.ArrayOfType(new a.InstanceOfType(a.Attribute)),devoid:function(){return{}},filter:function(b){var d=[],c;for(c in b)d.push(new a.Attribute(a.merge({key:c},
b[c])));return d},writer:null}));j.push(new a.Attribute({key:"methods",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null}));j.push(new a.Attribute({key:"around",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null}));j.push(new a.Attribute({key:"before",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null}));j.push(new a.Attribute({key:"after",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null}));
h=a.Trait.prototype;g=0;for(l=j.length;g<l;g++)j[g].install(h);a.Constructor=a.construct(function(b){var d=new a.Trait(b);b=function(a){d.setFromArgs(this,a)};d.install(b.prototype);return b})}).call(this);
