// o.js : v0.0.7 : http://o-js.com : MIT License
(function(){function m(a){return a.charAt(0).toUpperCase()+a.slice(1)}var j=this,n=j.o,a={};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=a),exports.o=a,exports.oJS=a):(j.o=a,j.oJS=a);a.noConflict=function(){j.o=n;return a};a.reader=function(d,c){c=c||{};c.writer=c.writer||a.writer(d,c);c.predicate=c.predicate||a.predicate(d);return function(){if(!c.predicate.call(this)){if(c.required)throw Error("...");if(void 0!==c.devoid){var a=c.devoid;a instanceof
Function&&(a=a.call(this));c.writer.call(this,a)}}return this[d]}};a.writer=function(d,c){c=c||{};c.augments&&(c.type=c.type||"object");return function(b){c.filter&&(b=c.filter.call(this,b));if(c.type)if("string"===typeof c.type||c.type instanceof String){if(typeof b!==c.type)throw Error("...");}else if(c.type instanceof Function){if(!c.type(b))throw Error("...");}else if(c.type instanceof a.Type)c.coerce?b=c.type.coerce(b):c.type.validate(b);else throw Error("...");if(c.augments&&!(b instanceof c.augments))throw Error("...");
var f=this[d];this[d]=b;return c.chain?this:f}};a.accessor=function(d,c){c=c||{};c.writer=c.writer||a.writer(d,c);c.reader=c.reader||a.reader(d,c);return function(a){return void 0!==a?c.writer.call(this,a):c.reader.call(this)}};a.predicate=function(d){return function(){return a.has(this,d)&&void 0!==this[d]}};a.clearer=function(a){return function(){delete this[a]}};a.proxy=function(a,c){return function(){return this[a][c].apply(this[a],arguments)}};a.before=function(a,c){return function(){c.call(this);
return a.apply(this,arguments)}};a.after=function(a,c){return function(){var b=a.apply(this,arguments);c.call(this);return b}};a.around=function(a,c){return function(){var b=this,f=Array.prototype.slice.call(arguments);f.unshift(function(){return a.apply(b,arguments)});return c.apply(b,f)}};a.construct=function(d,c){a.merge(d.prototype,c);return d};a.augment=function(d,c,b){var f=a.around(d,c);b=b?a.merge({},c.prototype,b):a.clone(c.prototype);b.__proto__=d.prototype;f.prototype=b;return f};a.merge=
function(){for(var d=Array.prototype.slice.call(arguments),c=d.shift();d.length;){var b=d.shift(),f;for(f in b)a.has(b,f)&&(c[f]=b[f])}return c};a.clone=function(d){var c=a.merge({},d);c.__proto__=d.__proto__;c.constructor=d.constructor;return c};a.has=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};a.Type=a.construct(function(a){"function"===typeof a&&(a={validate:a});if(a.validate)this.validateMethod=a.validate;else throw Error("...");a.message&&(this.messageMethod=a.message);a.coerce&&
(this.coerceMethod=a.coerce);a.parent&&(this.parent=a.parent)},{check:function(a){return this.parent&&!this.parent.check(a)||!this.validateMethod(a)?!1:!0},validate:function(a){this.parent&&this.parent.validate(a);if(!this.validateMethod(a))throw Error("...");return!0},coerceOnly:function(a){this.parent&&(a=this.parent.coerceOnly(a));this.coerceMethod&&(a=this.coerceMethod(a));return a},coerce:function(a){a=this.coerceOnly(a);if(!this.validateMethod(a))throw Error("...");return a},error:function(a){if(this.messageMethod)throw Error(this.messageMethod(a));
throw Error('Validation failed for value "'+a+'"');},subtype:function(d){"function"===typeof d&&(d={validate:d});void 0===d.validate&&(d.validate=function(){return!0});return new a.Type(a.merge({parent:this},d))}});a.EqualType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){return a===c?!0:!1};a(b)});a.AnyType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){for(var d=0,b=c.length;d<b;d++)if(c[d].check(a))return!0;return!1};a(b)});a.AllType=a.augment(a.Type,function(a,
c,b){b=b||{};b.validate=function(a){for(var d=0,b=c.length;d<b;d++)if(!c[d].check(a))return!1;return!0};a(b)});a.NoneType=a.augment(a.Type,function(d,c,b){b=b||{};var f=new a.AnyType(c);b.validate=function(a){return f.check(a)?!1:!0};d(b)});a.NotType=a.augment(a.NoneType,function(a,c,b){a([c],b)});a.EnumType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){for(var d=0,b=c.length;d<b;d++)if(a===c[d])return!0;return!1};a(b)});a.TypeOfType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=
function(a){return typeof a===c?!0:!1};a(b)});a.InstanceOfType=a.augment(a.Type,function(a,c,b){b=b||{};b.validate=function(a){return a instanceof c?!0:!1};a(b)});a.undefinedType=new a.EqualType(void 0);a.definedType=new a.NotType(a.undefinedType);a.nullType=new a.EqualType(null);a.booleanPrimitiveType=new a.TypeOfType("boolean");a.booleanObjectType=new a.InstanceOfType(Boolean);a.booleanType=new a.AnyType([a.booleanPrimitiveType,a.booleanObjectType]);a.stringPrimitiveType=new a.TypeOfType("string");
a.stringObjectType=new a.InstanceOfType(String);a.stringType=new a.AnyType([a.stringPrimitiveType,a.stringObjectType]);a.nonEmptyStringType=a.stringType.subtype(function(a){return 0<a.length?!0:!1});a.numberPrimitiveType=new a.TypeOfType("number");a.numberObjectType=new a.InstanceOfType(Number);a.numberType=new a.AnyType([a.numberPrimitiveType,a.numberObjectType]);a.integerType=a.numberType.subtype(function(a){return Math.floor(a)===a+0?!0:!1});a.positiveType=a.numberType.subtype(function(a){return 0<
a?!0:!1});a.negativeType=a.numberType.subtype(function(a){return 0>a?!0:!1});a.nonZeroType=a.numberType.subtype(function(a){return 0!==a?!0:!1});a.objectType=new a.InstanceOfType(Object);a.functionType=new a.InstanceOfType(Function);a.arrayType=new a.InstanceOfType(Array);a.regExpType=new a.InstanceOfType(RegExp);a.dateType=new a.InstanceOfType(Date);a.DuckType=a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(b){if(!a.objectType.check(b))return!1;for(var d=0,e=c.length;d<e;d++)if(void 0===
b[c[d]])return!1;return!0};d(b)});a.ArrayOfType=a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(b){if(!a.arrayType.check(b))return!1;for(var d=0,e=b.length;d<e;d++)if(!c.check(b[d]))return!1;return!0};d(b)});a.ObjectOfType=a.augment(a.Type,function(d,c,b){b=b||{};b.validate=function(b){if(!a.objectType.check(b))return!1;for(var d in b)if(!c.check(b[d]))return!1;return!0};d(b)});var e=new a.AnyType([a.nullType,a.nonEmptyStringType]),e={key:{type:a.nonEmptyStringType,required:!0},argKey:{type:new a.AnyType([a.nonEmptyStringType,
a.nullType]),devoid:function(){return this.key()}},valueKey:{type:a.nonEmptyStringType,devoid:function(){return"_"+this.key()}},devoid:{type:a.definedType},required:{type:a.booleanType,devoid:!1},type:{type:new a.AnyType([new a.EnumType("undefined object boolean number string function".split(" ")),new a.InstanceOfType(a.Type),a.functionType])},coerce:{type:a.booleanType,devoid:!1},filter:{type:a.functionType},augments:{type:a.functionType},chain:{type:a.booleanType,devoid:!1},reader:{type:e,devoid:function(){return this.key()}},
writer:{type:e,devoid:function(){return this.key()}},predicate:{type:e,filter:function(a){!0===a&&(a="has"+m(this.key()));return a},devoid:function(){return null}},clearer:{type:e,filter:function(a){!0===a&&(a="clear"+m(this.key()));return a},devoid:function(){return null}},proxies:{type:new a.ObjectOfType(a.nonEmptyStringType)}},l={},k={},g;for(g in e)l[g]=a.writer("_"+g,e[g]),k[g]=a.reader("_"+g,a.merge({writer:l[g]},e[g]));a.Attribute=a.construct(function(d){this._originalArgs=a.clone(d);for(var c in d)l[c].call(this,
d[c])},a.merge({readerMethod:a.reader("_readerMethod",{type:a.functionType,devoid:function(){return a.reader(this.valueKey(),{devoid:this.devoid(),required:this.required(),writer:this.writerMethod(),predicate:this.predicateMethod()})}}),writerMethod:a.reader("_writerMethod",{type:a.functionType,devoid:function(){return a.writer(this.valueKey(),{type:this.type(),coerce:this.coerce(),filter:this.filter(),augments:this.augments(),chain:this.chain()})}}),accessorMethod:a.reader("_accessorMethod",{type:a.functionType,
devoid:function(){return a.accessor(this.valueKey(),{writer:this.writerMethod(),reader:this.readerMethod()})}}),predicateMethod:a.reader("_predicateMethod",{type:a.functionType,devoid:function(){return a.predicate(this.valueKey())}}),clearerMethod:a.reader("_clearerMethod",{type:a.functionType,devoid:function(){return a.clearer(this.valueKey())}}),proxyMethods:a.reader("_proxyMethods",{type:new a.ObjectOfType(a.functionType),devoid:function(){var a={},c=this.proxies();if(void 0===c)return a;var b=
this,f;for(f in c)a[f]=function(a){return function(){var c=b.getValue(this);return c[a].apply(c,arguments)}}(c[f]);return a}}),getValue:function(a){return this.readerMethod().call(a)},setValue:function(a,c){return this.writerMethod().call(a,c)},hasValue:function(a){return this.predicateMethod().call(a)},clearValue:function(a){return this.clearerMethod().call(a)},setValueFromArgs:function(a,c){if(null!==this.argKey()&&void 0!==c[this.argKey()])return this.setValue(a,c[this.argKey()])},install:function(a){null!==
this.writer()&&this.writer()===this.reader()?a[this.writer()]=this.accessorMethod():(null!==this.writer()&&(a[this.writer()]=this.writerMethod()),null!==this.reader()&&(a[this.reader()]=this.readerMethod()));null!==this.predicate()&&(a[this.predicate()]=this.predicateMethod());null!==this.clearer()&&(a[this.clearer()]=this.clearerMethod());var c=this.proxyMethods(),b;for(b in c)a[b]=c[b]},rebuild:function(d){return new this.constructor(a.merge({},this._originalArgs,d))}},k));var h=[];a.Trait=a.construct(function(a){for(var c=
0,b=h.length;c<b;c++)h[c].setValueFromArgs(this,a)},{install:function(d){for(var c=this.traits(),b=0,f=c.length;b<f;b++)c[b].install(d);c=this.attributes();b=0;for(f=c.length;b<f;b++)c[b].install(d);var b=this.methods(),e;for(e in b)d[e]=b[e];b=this.around();for(e in b)d[e]=a.around(d[e],b[e]);b=this.before();for(e in b)d[e]=a.before(d[e],b[e]);b=this.after();for(e in b)d[e]=a.after(d[e],b[e])},setFromArgs:function(a,c){for(var b=this.attributes(),e=0,g=b.length;e<g;e++)b[e].setValueFromArgs(a,c)}});
h=[{key:"traits",type:new a.ArrayOfType(new a.InstanceOfType(a.Trait)),devoid:function(){return[]},writer:null},{key:"attributes",type:new a.ArrayOfType(new a.InstanceOfType(a.Attribute)),devoid:function(){return{}},filter:function(d){var c=[],b;for(b in d){var e=d[b];e instanceof a.Attribute?e.key()!==b&&(e=e.rebuild({key:b})):e=new a.Attribute(a.merge({},e,{key:b}));c.push(e)}return c},writer:null},{key:"methods",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null},{key:"around",
type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null},{key:"before",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null},{key:"after",type:new a.ObjectOfType(a.functionType),devoid:function(){return{}},writer:null}];g=a.Trait.prototype;e=0;for(k=h.length;e<k;e++)h[e]=new a.Attribute(h[e]),h[e].install(g);a.Constructor=a.construct(function(d){var c=new a.Trait(d);d=function(a){c.setFromArgs(this,a)};c.install(d.prototype);return d})}).call(this);
