++++
<table><tr>
<td><a href="https://o-js.com">o-js.com</a></td>
<td><a href="Overview.adoc">Overview</a></td>
<td><a href="Cookbook.adoc">Cookbook</a></td>
<td><strong>Classes</strong></td>
<td><a href="Traits.adoc">Traits</a></td>
<td><a href="Attributes.adoc">Attributes</a></td>
<td><a href="Types.adoc">Types</a></td>
<td><a href="Plumbing.adoc">Plumbing</a></td>
</tr></table>
++++

= Classes

*link:#synopsis[Synopsis]* +
*link:#description[Description]* +
*link:#attributes[Attributes]*

== Synopsis

```js
var Person = new o.Class({
    attributes: {
        firstName: { type:o.nonEmptyStringType, required:true },
        lastName: { type:o.nonEmptyStringType, required:true },
        age: { type:new o.AllType([ o.positiveType, o.integerType ]), required:true }
    },
    methods: {
        fullName: function () { return this.firstName + ' ' + this.lastName }
    }
});

var bilbo = new Person({
    firstName: 'Bilbo',
    lastName: 'Baggins',
    age: 111
});

console.log( bilbo.fullName() ); // Bilbo Baggins
```

== Description

`o.Class` is a thin wrapper around a `o.Trait` and accepts all the same arguments.  The
underlying trait of the class is installed on the class's prototype so that any objects
created by the class have the trait automatically applied.

See the link:Traits.adoc[Traits Documentation] for what arguments this accepts.

Constructors created by `o.Class` have an internal-only trait assigned to them called
`o.classTrait` which exposes a `type` and a `trait` attribute.

```js
    Person.type.check( bilbo ); // true
    var frodo = Person.type.coerce({ firstName:'Frodo', lastName:'Baggins', age:33 });
    Person.type.check( frodo ); // true
```

== Attributes

All classes get the following attributes.

=== type

    <type> = <class>.type;

Returns an `o.InstanceOfType` set to the class.

Note that duck types can provide a lot more flexibility, so instead of using this
you may want to use the trait's type, as in:

```js
var class = new o.Class({});
var instanceOfType = class.type;
var duckType = class.trait.type; // <- this one
```

=== trait

    <trait> = <class>.trait;

Returns the trait which the class uses to construct new objects.

