++++
<table><tr>
<td><a href="https://o-js.com">o-js.com</a></td>
<td><a href="Overview.adoc">Overview</a></td>
<td><strong>Cookbook</strong></td>
<td><a href="Classes.adoc">Classes</a></td>
<td><a href="Traits.adoc">Traits</a></td>
<td><a href="Attributes.adoc">Attributes</a></td>
<td><a href="Types.adoc">Types</a></td>
<td><a href="Plumbing.adoc">Plumbing</a></td>
</tr></table>
++++

= Cookbook

*link:#custom-types[Custom Types]* +
*link:#using-types-standalone[Using Types Standalone]* +
*link:#disabling-validation[Disabling Validation]* +
*link:#lite-classes[Lite Classes]*

== Custom Types

The base class for all type classes and objects is the `o.Type` class.  Under normal
circumstances you should be able to construct custom types using the existing
pre-defined type classes and object documented in the link:types.adic[Types doc].

For example, you could create a type which validates that a number is an integer,
and is zero or positive with:

```js
var type = new o.AllType([
    o.integerType,
    new o.AnyType([
        new o.EqualType( 0 ),
        o.positiveType
    ])
]);
```

But, sometimes you need to construct a type yourself using custom rules.  To do that,
create an instance of `o.Type`:

```js
var type = new o.Type({
    validate: function (val) {
        if (Math.floor(val) !== val + 0) return false;
        if (val < 0) return false;
        return true;
    }
});
```

Another alternative to this is creating you own type class by augmenting the `o.Type`
class:

```js
var MyType = o.augment(
    o.Type,
    function (parent, min, args) {
        args = args || {};
        args.validate = function (val) {
            if (Math.floor(val) !== val + 0) return false;
            if (val < min) return false;
            return true;
        };
        parent( args );
    }
);
var type = new MyType( 0 );
```

All three of the above examples produce a type which validates using the same
rules.  Each example is more complex than the previous, but is also more powerful.

== Using Types Standalone

Types can be used independently of the rest of o.js, such as in conjunction with
form validation libraries.  If you'd like to check if a value is valid, or not,
use the `check()` function:

```js
if (o.integerType.check( value )) {
    // Do something with the valid value.
}
```

If you'd like an exception to be thrown you can use the `validate()` function.

```js
o.nonEmptyStringType.validate( value );
// Do something with the valid value.
```

And if you'd like to apply coercion you can do that too with `coerce()`.  It is
recommended that your coercion function be relaxed and produce bad data if it is
given bad data.  It is not the coercion function's job to validate.

```js
var roundNum = o.numberType.subtype({
    coerce: function (val) { return Math.round(val) }
});
var value = 2.5;
value = roundNum.coerce( value ); // 3
roundNum.validate( value ); // Make sure the coerced value is valid.
```

== Disabling Validation

Validation may be disabled by calling:

```js
o.disableTypeValidation();
```

Doing this depends heavily on what validation means to you.  If validation is a tool
for which you depend on during development and testing to find bugs before deployment
then you may find that the performance gain of disabling validation in production may
be worth the loss of early error detection you get by enabling validation.

Another workflow is to disable validation for specific blocks of code:

```js
// Validation is enabled here.
o.disableTypeValidation(function(){
    // Validation is disabled here.
});
// Validation is enabled here.
```

Doing the above may be useful if you have certain pieces of code which spawn many
objects and the performance gain of disabling validation within a scope is worth it.

== Lite Classes

Classes in o.js can be a little top-heavy for certain use cases due to every property
having custom setter and getter functions.  If you're willing to sacrifice the benefits
of the function calls (validation, etc) for the speed of direct property access then
you can apply the `lite` class trait:

```js
var Person = new o.Class({
    is: 'lite',
    attributes: { foo:{} }
});

var p = new Person({ foo:'abc' });
console.log( p.foo ); // abc
```

This trait will *only* apply to new attributes - any attributes applied by other traits
will be setup in whatever way they were configured in their respective trait.

Read more about this at the link:Traits.adoc#is[Traits doc].

You can also apply this trait per-attribute:

```js
var Person = new o.Class({
    attributes: {
        foo: { is:'lite' }
    }
});
```

