++++
<table><tr>
<td><a href="https://o-js.com">o-js.com</a></td>
<td><a href="Overview.adoc">Overview</a></td>
<td><a href="Cookbook.adoc">Cookbook</a></td>
<td><a href="Classes.adoc">Classes</a></td>
<td><a href="Traits.adoc">Traits</a></td>
<td><a href="Attributes.adoc">Attributes</a></td>
<td><a href="Types.adoc">Types</a></td>
<td><strong>Plumbing</strong></td>
</tr></table>
++++

= Plumbing

*link:#utilities[Utilities]* +
*link:#function-modifiers[Function Modifiers]* +
*link:#properties[Properties]*

== Utilities

=== construct

    <constructor> = o.construct( <constructor>, <prototype> );

```js
var Person = o.construct(
    function (args) { this.age = args.age },
    {
        hoursOld: function () {
            return this.age * 365 * 24;
        }
    }
);
var bilbo = new Person({ age: 111 });
console.log( bilbo.hoursOld() ); // 972,360
```

Provides shorthand for creating a new constructor with a prototype.  The `prototype` will
be merged in to the prototype of the passed `constructor`.

=== augment

    <newConstructor> = o.augment( <parentConstructor>, <constructor>, [<prototype>] )

```js
var Point2D = function(x, y){ this.x=x; this.y=y };
var Point3D = o.augment(
    Point2D,
    function (orig, x, y, z) {
        orig( x, y );
        this.z = z;
    }
);
```

Uses `o.around` where `parentConstructor` is the `origFunction` and `constructor` is
the `aroundFunction`.  The prototype of the `newConstructor` will be set to inherit from
the prototype of the `parentConstructor`, and if `prototype` is specified then it will be
merged into the prototype of the `newConstructor`.

Typically, in JavaScript inheritance, all that is setup is prototype inheritance.  This
function takes this a step further by also inheriting the constructor function so that
construction logic is maintained in the inheriting constructor.

=== merge

    <object1> = o.merge( <object1>, <object2> [...] );

```js
var merged = o.merge({a:1,b:1}, {b:2,c:2}, {c:3,d:3});
// {a:1, b:2, c:3, d:3}
```

Takes the first object and merges all subsequent objects in to it.  The farther right in
the list the object is, the higher its precedence is.  Returns the first object.

=== clone

    <newObject> = o.clone( <object> );

```js
var obj1 = {foo:'bar'};
var obj2 = o.clone( obj1 );
console.log( obj2.foo ); // 'bar'
```

Clones the object by returning a new one with the same keys and values, constructor,
and prototype.

=== has

    <boolean> = o.has( <object>, <key> );

```js
var obj = {foo:'bar'};
if (o.has(obj, 'foo')) { /* do something */ }
```

This is just shorthand for calling `hasOwnProperty`.

=== local

    o.local( <object>, <property>, <function> );

```js
var obj = { foo: 32 };
o.local( obj, 'foo', function(){
    console.log( obj.foo ); // 32
    obj.foo = 501;
    console.log( obj.foo ); // 501
});
console.log( obj.foo ); // 32
```

Within the scope of the function this will localize the specified `property` on the
`object`.  This way the property can be changed and any called code will then see the
new property value.  When scope leaves the function the property will be restored to
its original value.  This is useful for modifying global variables without making a
permanent global impact.

If an exception is thrown during the function's execution the exception will be caught,
the property will still be restored to its original value, and the exception will be
rethrown.

=== ucFirst

    <string> = o.ucFirst( <string> );

```js
o.ucFirst( 'foo' ); // Foo
```

This function just uppercases the first character of the string and returns the
new string.

=== prependIdentifier

    <string> = o.prependIdentifier( <prependString>, <identifierString> );

```js
o.prependIdentifier('set', 'foo'); // setFoo
o.prependIdentifier('_set', 'foo'); // _setFoo
o.prependIdentifier('_set', '_foo'); // _setFoo
o.prependIdentifier('_', 'foo'); // _foo
o.prependIdentifier('_', '_foo'); // _foo
```

This function prepends the passed string to the idenitfier using best-practices for
identifier naming, specifically special attention is made to uppercasing the first
character of the `identifierString` if `prependString` is non-empty and not equal to
just `_`, as well as if either or both of the `prependString` and `identifierString`
arguments are private (start with a `_`) then the returned identifier will also be
private.

== Function Modifiers

=== before

    <newFunction> = o.before( <origFunction>, <beforeFunction> );

```js
var main = function () { console.log('main') };
var before = function () { console.log('before') };
var combined = o.before( main, before );
combined(); // Logs "before", then "main".
```

Creates a new function where the `beforeFunction` will be called before the `origFunction`.

=== after

    <newFunction> = o.after( <origFunction>, <afterFunction> );

```js
var main = function () { console.log('main') };
var after = function () { console.log('after') };
var combined = o.after( main, after );
combined(); // Logs "main", then "after".
```

Creates a new function where the `afterFunction` will be called after the `origFunction`.

=== around

    <newFunction> = o.around( <origFunction>, <aroundFunction> );

```js
var main = function (number) { console.log(number) };
var around = function (orig, number) { return orig(number + 1) };
var combined = o.around( main, around );
combined(2); // Logs 3.
```

Creates a new function where the `aroundFunction` will be called with an extra first
argument, a function that will call the origFunction.

== Properties

=== reader

    <readerFunction> = o.reader( <propNameString>, <argsObject> );

```js
var zReader = o.reader('z');
var obj = {z:3};
console.log( zReader.call(obj) ); // 3
```

Creates a function which will read the specified property key and apply various
behaviors as part of that reading.

The `argsObject` can have the following properties set:

writer::
    A function as produced by `o.writer`.  If none is specified one will be
    automatically created.
predicate::
    A function as produced by `o.predicate`.  If none is specified one will
    be automatically created.
required::
    A boolean.  If set to `true` then an exception will be thrown if the
    property has not yet been set.
devoid::
    A function which is expected to return a value for the property if the
    property is undefined.  The value returned will be written to the property
    using the `writer`.
builder::
    The name of a function to call on `this` if the property is not yet set.
    Works just like `devoid` except this is a function name rather than the
    function itself.

This function provides a lot of the moving parts behind `o.Attribute`, so go see
the link:Attributes.adoc[Attributes doc] for more information.

=== writer

    <writerFunction> = o.writer( <propNameString>, <argsObject> );

```js
var zWriter = o.writer('z');
var obj = {};
zWriter.call(obj, 4);
console.log( obj.z ); // 4
```

Creates a function which will write a value to the specified property and apply
various behaviors as part of that writing.

The `argsObject` can have the following properties set:

augments::
    Set this to a constructor function and if a value is attempted to be written which
    is either not an object or not a `instanceof` the constructor an exception will be
    thrown.
type::
    Set this to either a string (which will be used in a `typeof` comparison), a function
    (which will be passed the value and is expected to return `true` or `false`), or an
    `o.Type` object.  If the type validation fails an exception will be thrown.
filter::
    Set this to a function which will be passed a value and is expected to return a filtered
    value.  Filtering is done before type checking.
coerce::
    Set this to `true` to enable coercion as provided by an `o.Type` object set via the
    `type` argument.  Coercion will be applied before type checking.

This function provides a lot of the moving parts behind `o.Attribute`, so go see
the link:Attributes.adoc[Attributes doc] for more information.

=== predicate

    <predicateFunction> = o.predicate( <propNameString> );

```js
var zPredicate = o.predicate('z');
var obj = {};
console.log( zPredicate.call( obj ) ); // false
obj.z = 123;
console.log( zPredicate.call( obj ) ); // true
```

Create a function which checks if the property is undefined.

=== clearer

    <clearerFunction> = o.clearer( <propNameString> );

```js
var zClearer = o.clearer('z');
var obj = {z:567};
zClearer.call( obj );
console.log( obj.z ); // undefined
```

Creates a function which deletes the property.

