++++
<table><tr>
<td><a href="https://o-js.com">o-js.com</a></td>
<td><a href="Overview.adoc">Overview</a></td>
<td><a href="Cookbook.adoc">Cookbook</a></td>
<td><a href="Classes.adoc">Classes</a></td>
<td><strong>Traits</strong></td>
<td><a href="Attributes.adoc">Attributes</a></td>
<td><a href="Types.adoc">Types</a></td>
<td><a href="Plumbing.adoc">Plumbing</a></td>
</tr></table>
++++

= Traits

*link:#synopsis[Synopsis]* +
*link:#description[Description]* +
*link:#declarative-interface[Declarative Interface]* +
*link:#arguments[Arguments]* +
*link:#attributes[Attributes]* +
*link:#methods[Methods]*

== Synopsis

```js
var playerTrait = new o.Trait({
    attributes: {
        id: { type:o.integerType, required:true },
        name: { type:o.nonEmptyStringType, required:true }
    }
});

var Computer = new o.Class({
    traits: [ playerTrait ],
    attributes: {
        difficulty: { type:o.enumType(['easy', 'hard']), devoid:'easy' }
    }
});

var Human = new o.Class({
    traits: [ playerTrait ]
});

var human = new Human({ id:1, name:'Fischer' });
var computer = new Computer({ id:2, name:'Blue', difficulty:'hard' });
```

Trait may be applied to an existing object if you are not using `o.Class`:

```js
var customPlayer = {};
playerTrait.install( customPlayer, { id:3, name:'Bob' } );
```

You may even roll your own custom constructor and apply traits there:

```js
var Player = function (args) {
    playerTrait.install( this, args );
};
var customPlayer = new Player({ id:4, name:'Lisa' });
```

== Description

`o.Trait` creates a trait object which can be applied to other objects,
extending their functionality with the trait's interface.  Trait objects
can also be used with the `traits:[]` arguments to `o.Class` and `o.Trait`.
Multiple traits can be applied to a single object, bypassing JavaScript's
single-inheritance model, supporting the
http://en.wikipedia.org/wiki/Composition_over_inheritance[Composition over Inheritance]
technique.

== Declarative Interface

Instead of passing an object as the argument you may pass an anonymous function
which will be called with a custom `this` variable containing functions for
declaring your trait's properties.  So, for example, you could write this:

```js
var PlayerTrait = new o.Trait(function(){
    this.attribute( 'id', { type:o.integerType, required:true } );
});
```

The following functions are available when using the declarative syntax:

```js
this.require( propertyName );
this.is( classTraitName );
this.trait( trait );
this.attributesAre( attributeTraitName );
this.attributeTrait( trait );
this.attribute( name, args );
this.method( name, func );
this.around( name, func );
this.before( name, func );
this.after( name. func );
```

This declarative syntax, while slightly more verbose, gives a lot more
flexibility for dynamically constructing traits and classes.

== Arguments

=== attributes

    [attributes: <objectOfAttributes>]

```js
attributes: {
   attrOne: attrObject, // An o.Attribute object.
   attrTwo: { /* o.Attribute arguments */ }
}
```

An object containing link:Attributes.adoc[Attribute] objects, or arguments to create them,
where the key will be used as the attribute's `key` argument.  If an attribute object
is passed, rather than arguments for one, and the attribute's key does not match then
the attribute's `rebuild()` method will be called to create a new attribute object with
the specified key.

=== is

    [is: <traitName>]

```js
is: 'lite'
```

Applies one of the `o.<traitName>ClassTrait` traits.  The currently available traits are:

lite::
    Sets the `is` argument for all new attributes to `lite`.

=== traits

    [traits: <arrayOfTraits>]

```js
traits: [ TraitOne, TraitTwo ]
```

An array of traits which will be installed to the target object before this trait is installed.

=== attributesAre

    [attributesAre: <traitName>]

```js
attributesAre: 'rw'
```

Setting this causes all new attributes to have their `is` argument set to
this value.

Read more about this at the link:Attributes.adoc#is[Attributes doc].

=== attributeTraits

    [attributeTraits: <arrayOfTraits>]

```js
attributeTraits: [ TraitOne, TraitTwo ]
```

Setting this causes all new attributes to have their `traits` argument set
to this value.

Read more about this at the link:Attributes.adoc#traits[Attributes doc].

=== requires

    [requires: <duckType>]

```js
requires: ['propOne', 'propTwo']
requires: {propOne:o.stringType, propTwo:o.functionType]
```

If this is set to an instance of `o.DuckType` the object that the trait is installed onto
must pass the duck type check.  This argument support coercion, so if you pass arguments
which are supported by the `o.DuckType` constructor they will be automatically used to
create an `o.DuckType` object for you.

=== methods

    [methods: <objectOfMethods>]

```js
methods: {
    increase: function (amount) {
        this.value( this.value() + amount );
    }
}
```

An object containing functions where the key will be the name of the function.

=== around

    [around: <objectOfAroundModifiers>]

```js
around: {
    save: function (orig, data) {
        console.log('Saving ' + data + '...');
        orig( data );
        console.log('Saved!');
    }
}
```

Wraps the the specified method in a function, allowing you to do things before and
after the method call, change the argument, or even decide not to call the original method.

=== before

    [before: <objectOfBeforeModifiers>]

```js
before: {
   save: function () { console.log('Saving...') }
}
```

Calls the specified function before calling the underlying method.

=== after

    [after: <objectOfAfterModifiers>]

```js
after: {
   save: function () { console.log('Saved!') }
}
```

Calls the specified function after calling the underlying method.

== Attributes

=== type

    <type> = <trait>.type;

Returns a `o.DuckType` which is keyed to look for objects which appear to have this
trait.

== Methods

=== install

    <trait>.install( <object>, [<arguments>] )

```js
MyTrait.install( myObject );
// Now myObject has all the attributes, methods, etc, provided by MyTrait.
```

Installs the trait's interface onto an object.  If an arguments object is passed then
then `setFromArgs` will be called for you after the install is done.

=== setFromArgs

    <trait>.setFromArgs( <object>, <arguments> )

```js
MyTrait.setFromArgs( myObject, { /* arguments */ } );
```

Applies the arguments to the object via the trait's (and any traits in the
`traits:[]` argument) attributes.

