++++
<table><tr>
<td><a href="https://o-js.com">o-js.com</a></td>
<td><a href="Overview.adoc">Overview</a></td>
<td><a href="Cookbook.adoc">Cookbook</a></td>
<td><a href="Classes.adoc">Classes</a></td>
<td><a href="Traits.adoc">Traits</a></td>
<td><a href="Attributes.adoc">Attributes</a></td>
<td><strong>Types</strong></td>
<td><a href="Plumbing.adoc">Plumbing</a></td>
</tr></table>
++++

= Types

*link:#objects[Objects]* +
*link:#classes[Classes]* +
*link:#arguments[Arguments]* +
*link:#methods[Methods]*

== Objects

Many type objects are already defined for all of the built-in JavaScript types.  Below is
the list of the types that are currently available.  These type objects are all instances
of the `o.Type` class.

```text
undefined
defined
    null
    boolean
        booleanPrimitive
        booleanObject
    string
        stringPrimitive
        stringObject
        nonEmptyString
        identifier
    number
        numberPrimitive
        numberObject
        integer
        positive
        posotiveInt
        negative
        nonZero
    object
        function
        array
        regExp
        date
        simpleObject
        class
        trait
        attribute
        type
```

To use these type objects just prefix them with `o.` and suffix them with `Type`, so
`integer` becomes `o.integerType`.  For example:

```js
var Person = new o.Class({
    attributes: {
        age: { type: o.integerType }
    }
});
```

The `simpleObject` type subtypes the `object` type and additionally checks that the
value's constructor is `Object`.

The `class`, `trait`, `attribute`, and `type` types are used to validate that a
given object is an instance of the `o.Class`, `o.Trait`, `o.Attribute`, and `o.Type`
constuctors.  Each of these types has a coercion defined which checks if the value
is a `simpleObject`, and if it is it uses the value as arguments for creating
an appropriate object.  So, for example these two lines do the same thing:

```js
obj = new o.Trait({});
obj = o.traitType.coerce({});
```

== Classes

Type classes are used to construct complex types that solve common problems.  These
classes all inherit from the `o.Type` class and support all its arguments and methods.

These classes all accept two arguments.  The first argument is defined by the
individual class and is required.  The second argument is optional and, if present,
must be an object containing arguments as accepted by link:#type[o.Type].

=== EqualType

    <type> = new o.EqualType( <value>, [<arguments>] )

```js
var greenType = new o.EqualType('green');
if (greenType.check('green')) console.log('green is green');
if (!greenType.check('blue')) console.log('blue is not green');
```

Creates a type that validates that the passed in value passes a strict comparison
against the `<value>` argument.

=== AnyType

    <type> = new o.AnyType( <typesArray>, [<arguments>] )

```js
var numOrStrType = new o.AnyType([ o.integerType, o.stringType ]);
if (numOrStrType.check(1)) console.log('1 is a num or str');
if (numOrStrType.check('a')) console.log('"a" is a num or str');
if (!numOrStrType.check(null)) console.log('null is not a num or str');
```

This type class creates a type that verifies that the passed in value passes at least
one of the types in `<typesArray>`.

=== AllType

    <type> = new o.AllType( <typesArray>, [<arguments>] )

Similar to `o.AnyType`, this type class verifies that the passed in value passes every
single one of the types in `<typesArray>`.

=== NoneType

    <type> = new o.NoneType( <typesArray>, [<arguments>] )

This is the opposite of `o.AllType` in that value must not pass any of the types in
`<typesArray>`.

=== NotType

    <type> = new o.NotType( <type>, [<arguments>] );

```js
var notNullType = new o.NotType( o.nullType );
var foo = null;
if (!notNullType.check(null)) console.log('null is not not null');
if (notNullType.check(1)) console.log('1 is not null');
```

This inverts the given `<type>`'s validation, causing it to return `true` if it would
have returned `false`, and `false` if it would have returned `true`.

=== EnumType

    <type> = new o.EnumType( <valuesArray>, [<arguments>] )

```js
var rgbType = new o.EnumType( ['red', 'green', 'blue'] );
if (rgbType.check('red')) console.log('red is in rgb');
if (!rgbType.check('purple')) console.log('purple is not rgb');
```

Creates an enum type where the value must strictly match one of the
values in `<valuesArray>`.

=== TypeOfType

    <type> = new o.TypeOfType( <typeofString>, [<arguments>] )

```js
var stringType = new o.TypeOfType( 'string' );
if (stringType.check('foo')) console.log('string primitive is typeof string');
if (!stringType.check(new String('foo'))) console.log('string object is not typeof string')
```

Creates a type that validates that the value is `typeof` `<typeofString>`.  This is
actually how all the pre-defined primitive types are created, such as
`o.booleanPrimitiveType` and `o.numberPrimitiveType`.

Considering that all the types that `typeof` checks already have a corresponding
pre-defined type, there should be no need to use this type.

=== InstanceOfType

    <type> = new o.InstanceOfType( <constructor>, [<arguments>] )

```js
var Dog = function (name) { this.name=name };
var Cat = function (name) { this.name=name };
var fido = new Dog('Fido');
var whiskers = new Cat('Whiskers');
var isDogType = new o.instanceOfType( Dog );
if (isDogType.check(fido)) console.log('fido is a dog');
if (!isDogType.checl(whiskers)) console.log('whiskers is not a dog');
```

Creates a type that validates that the value is an `instanceof` the `<constructor>`
function.  Many of the pre-defined types are created using this, such as
`o.stringObjectType` and `o.arrayType`.

Typically a `DuckType` is a much better choice for validating objects than this type.

If the `constructor` was created by `o.Class` then a coercion will be declared on the
created type which will check if the value is a `simpleObject`, and if it is, it will
use the value as arguments to the constructor to create an instance.

=== DuckType

    <type> = new o.DuckType( <propertiesArray>, [<arguments>] )
    <type> = new o.DuckType( <propertiesObject>, [<arguments>] )

```js
var personType = new o.DuckType( ['name', 'age'] );
if (personType.check({name:'Bob', age:67})) console.log('bob is a person');
if (!personType.check({name:'Fido'})) console.log('fido is not a person');
```

If `<propertiesArray>` is passed then a type will be returned that validates that
the value is an object and that the object has the specified properties defined.

```js
var personType = new o.DuckType( {name:o.stringType, age:o.integerType} );
if (personType.check({name:'Fred', age:34})) console.log('fred looks like a person');
if (personType.check({name:'Ted', age:'98'})) console.log('ted does not look like a person.');
```

Instead of `<propertiesArray>` you can specify `<propertiesObject>` where the object
keys are the property names that must be defined on the value object, and the object
values are types that the value object's property values must pass.

Duck types are a great way to validate objects as they check that the object supports
an interface that you depend on, abstracting away what the object is, and focusing
on what the object does.

=== ArrayOfType

    <type> = new o.ArrayOfType( <type>, [<arguments>] )

```js
var arrayOfIntsType = new o.ArrayOfType( o.integerType );
if (arrayOfIntsType.check([1, 2, 3])) console.log('1,2,3 is an array of integers');
if (!arrayOfIntsType.check(['a', 'b', 'c'])) console.log('a,b,c is not an array of integers');
```

Creates a type that validates that the value is an array containing values that
match the `<type>`.

A coercion is declared on this type wich will coerce any values within the array using
the inner type's coercion logic (if any).

=== ObjectOfType

    <type> = new o.ObjectOfType( <type>, [<arguments>] )

Like `o.ArrayOfType`, but checks that the value is an object and that the key values
within the object match the `<type>`.

A coercion is declared on this type which will coerce any values within the object using
the inner type's coercion logic (if any).

=== TupleType

    <type> = new o.TupleType( <typesArray>, [<arguments>] )

```js
var type = new o.TupleType([ o.stringType, o.numberType ]);
if (type.check('abc',123)) console.log('abc,123 is my tuple');
if (!type.check(123,'abc')) console.log('123,abc is NOT my tuple');
```

Creates a type which validates that the passed array is a tuple where the ordered values
match the ordered types.  Too few values or two many will also cause the check the fail.

A coercion is declared on this type wich will coerce any values within the array using
the inner type's coercion logic (if any).

=== PatternType

    <type> = new o.PatternType( <RegExp>, [<arguments>] )

```js
var nameType = new o.PatternType(/^[A-Z][a-z]+$/);
if (nameType.check('George')) console.log('George looks like a name');
if (!nameType.check('george')) console.log('george does not look like a name');
```

Creates a type that checks that the values passes the `<RegExp>` pattern.

=== LazyType

    <type> = new o.LazyType( <function>, [<arguments>] );

```js
var type = new o.LazyType(function(){
    return new someCustomType();
});
```

This type is used internally to delay the definition of types until the moment
they are used.

=== Type

    <type> = new o.Type( <arguments> );

The `o.Type` class is the base class for all type classes and objects.  More information
about how to interact with this class can be found below at link:#arguments[Arguments]
and link:#methods[Methods], as well as at
link:Cookbook.adoc#custom-types[Custom Type Recipes].

== Arguments

These are the arguments which all type classes support.

=== validate

    validate: <function>

```js
validate: function (val) {
    if (valPassesSomeCondition) return true;
    return false;
}
```

The validate function is the heart of types.  It is what confirms whether or not a
value satisfies a constraint.  The validate function will be passed the value
to be checked and is expected to return `true` if it passes and `false` if not.

=== coerce

    [coerce: <function>]

```js
coerce: function (val) {
    if (valPassesSomeCondition) return val;
    return changeValToMatchCondition( val );
}
```

The coerce function is used to coerce a value which would not normally pass the
validation constraint.  This function should return the original, invalid, value
if it cannot be coerced.

=== parent

    [parent: <parentTypeObject>]

The parent type.  The parent type is used in validation and coercion.

== Methods

These are the methods which all type classes support.

=== check

    <type>.check( <value> )

```js
if (type.check(val)) doSomething();
```

Returns `true` if the passed value passes validation.  If the `parent` argument
has been set then the parent's validation will also be checked.
